### ISSUE TITLE
Infer fails to analyze App Engine project

### ISSUE THREAD

**Issue by sidky** [uber-common/infer-plugin#20]
I have an app engine module, along with an android module in the same project. Android infer works fine, but when I try to run infer for appengine module, it fails with:
```
$ ./gradlew :proxy:infer
Incremental java compilation is an incubating feature.
:proxy:inferCheckForCommand
:proxy:processResources UP-TO-DATE
:proxy:inferPrepare FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proxy:inferPrepare'.
> Configuration with name 'provided' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.997 secs
```
These are the tasks
```
$ ./gradlew :proxy:tasks
...
Infer tasks
-----------
eradicate - Runs Infer's eradicate static analysis.
infer - Runs Infer static analysis.
...
```

For app engine, I added:
`apply plugin: 'com.uber.infer.java'`
to my app-engine module's build.gradle

**Comment by clonetwin26** [comment]
Just double checking but app-engine is a java library? I would try it against 0.7.2, in which I think this is fixed. I will update the docs if this is the case.

**Comment by sidky** [comment]
Yes it is a java library

**Comment by sidky** [comment]
Yes, works for 0.7.2
