### ISSUE TITLE
Release new plugin

### ISSUE THREAD

**Issue by jaredsburrows** [uber-common/infer-plugin#23]
0.7.2 was released 2+ months ago.

Since this fix was added: https://github.com/uber-common/infer-plugin/pull/21 https://github.com/uber-common/infer-plugin/issues/13, there has not been another release.

Can we please do another release?

**Comment by clonetwin26** [comment]
Should be cut under 0.7.3

**Comment by jaredsburrows** [comment]
Thank you!
